# Publish all joint states -----------------------------------
head_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
head_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - head_pan_joint
    - head_tilt_joint
  #pid: {p: 100.0, i: 0.01, d: 10.0}
